USE DocOfficeNew;


-- APPOINTMENTS
SELECT APPOINTMENT.date, APPOINTMENT.doctor_Name
FROM APPOINTMENT
WHERE APPOINTMENT.Patient_ssn = "506-82-3169";

-- PRESCRIPTIONS
SELECT PRESCRIPTION.Drug_name, PRESCRIPTION.Dosage
FROM PRESCRIPTION
WHERE PRESCRIPTION.Patient_SSN = "429-10-0005";

-- TESTS
SELECT MEDICAL_TEST.Test_type, MEDICAL_TEST.Result
FROM MEDICAL_TEST
WHERE MEDICAL_TEST.Patient_SSN = "429-10-0005";

-- Patient Information 
SELECT City, Insurance_ID
FROM PATIENT 
WHERE SSN = "576-67-2311"; 

-- DOCTORS NEARBY
SELECT DOCTOR.First_name, DOCTOR.Specialty
FROM DOCTOR, PATIENT
WHERE PATIENT.SSN = "212-37-7116" AND PATIENT.City = DOCTOR.City;





SELECT * 
FROM PATIENT;

SELECT * 
FROM DOCTOR;
